bin/zbm-efi-kcl: allow pipelining via stdin/stdout

diff --git a/bin/zbm-efi-kcl b/bin/zbm-efi-kcl
--- a/bin/zbm-efi-kcl
+++ b/bin/zbm-efi-kcl
@@ -5,7 +5,10 @@ cleanup() {
   if [[ -f "${TEMP_EFI}" && -z "${PRESERVE_TEMP_EFI}" ]]; then
     rm "${TEMP_EFI}"
   fi
+
   [ -f "${TEMP_KCL}" ] && rm "${TEMP_KCL}"
+
+  [ -f "${TEMP_INPUT}" ] && rm "${TEMP_INPUT}"
 }
 
 clean_kcl() {
@@ -19,19 +22,32 @@ clean_kcl() {
   sed -i -z 's/\n/ /g' "${1}"
 }
 
+error() {
+  echo "ERROR: $*" >&2
+  exit 1
+}
+
 
 usage() {
   cat <<-EOF
-    USAGE: $0 [-e <arg>] [-f <arg>] [-k <arg>] [-o <arg>]
-    
-    -e <arg>  ZFSBootMenu EFI file
-    -f <arg>  Replace kernel command line with contents of file
-    -k <arg>  Replace kernel command line with quoted arguments
-    -o <arg>  Output file; if undefined the input file will be replaced
-    -p        Print the command line stored the input file and exit
+	USAGE: $0 [-e <arg>] [-f <arg>] [-k <arg>] [-o <arg>]
 
-    If neither -f, -k, or -p are provided, the command line from the
-    input EFI will be opened in \$EDITOR.
+	OPTIONS
+	  -e <arg>  ZFSBootMenu EFI file
+	  -f <arg>  Replace kernel command line with contents of file
+	  -k <arg>  Replace kernel command line with quoted arguments
+	  -o <arg>  Output file; if undefined the input file will be replaced
+	  -p        Print the command line stored in the input file and exit
+	  -h        Display this message and exit
+
+	If an input file is not provided with -e, the input executable will be
+	read from stdin. When reading input from stdin:
+
+	  - If -o is not provided, the result will be written to stdout.
+	  - One of -f, -k or -p is REQUIRED.
+
+	If neither -f, -k, or -p are provided, the command line from the
+	input EFI will be opened in \$EDITOR.
 	EOF
 }
 
@@ -39,18 +55,12 @@ INPUT_EFI=
 OUTPUT_EFI=
 ARG_FILE=
 ARG_VAR=
-PRINT_ONLY=0
+PRINT_ONLY=
 
-while getopts "e:f:k:o:p" opt; do
+while getopts "e:f:k:o:ph" opt; do
   case "${opt}" in
     e)
       INPUT_EFI="${OPTARG}"
-      if [ ! -f "${INPUT_EFI}" ]; then
-        echo "Unable to open ${INPUT_EFI}"
-        exit 1
-      fi
-      # Set OUTPUT_EFI to the input by default
-      [ -z "${OUTPUT_EFI}" ] && OUTPUT_EFI="${INPUT_EFI}"
       ;;
     o)
       # Override the output file
@@ -60,8 +70,7 @@ while getopts "e:f:k:o:p" opt; do
       ARG_FILE="${OPTARG}"
       ARG_VAR=
       if [ ! -f "${ARG_FILE}" ]; then
-        echo "Unable to open ${ARG_FILE}"
-        exit 1
+        error "Unable to open ${ARG_FILE}"
       fi
       ;;
     k)
@@ -69,7 +78,11 @@ while getopts "e:f:k:o:p" opt; do
       ARG_FILE=
       ;;
     p)
-      PRINT_ONLY=1
+      PRINT_ONLY=yes
+      ;;
+    h)
+      usage
+      exit 0
       ;;
     *)
       usage
@@ -78,23 +91,38 @@ while getopts "e:f:k:o:p" opt; do
   esac
 done
 
-if [ -z "${INPUT_EFI}" ]; then
-  usage
-  exit 1
-fi
-
 if ! command -v objcopy > /dev/null 2>&1 ; then
-  echo "Missing required binary 'objcopy'"
-  exit 1
+  error "Missing required binary 'objcopy'"
 fi
 
+if [ -n "${INPUT_EFI}" ] && [ ! -r "${INPUT_EFI}" ]; then
+  error "Unable to open ${INPUT_EFI}"
+fi
+
+# Set OUTPUT_EFI to the input by default
+if [ -z "${OUTPUT_EFI}" ]; then
+  OUTPUT_EFI="${INPUT_EFI}"
+fi
+
+TEMP_INPUT=
+TEMP_EFI=
+TEMP_KCL=
 trap cleanup EXIT INT TERM
+
+# Process EFI kcl on stdin if no input file was specified
+if [ -z "${INPUT_EFI}" ]; then
+  if [ -z "${ARG_FILE}" ] && [ -z "${ARG_VAR}" ] && [ -z "${PRINT_ONLY}" ]; then
+    error "reading from stdin requires one of -f, -k or -p"
+  fi
+
+  TEMP_INPUT="$(mktemp)"
+  cat > "${TEMP_INPUT}"
+  INPUT_EFI="${TEMP_INPUT}"
+fi
 
 TEMP_EFI="$(mktemp)"
 if ! objout="$( objcopy --remove-section .cmdline "${INPUT_EFI}" "${TEMP_EFI}" 2>&1 )"; then
-  echo "Unable to remove .cmdline from '${INPUT_EFI}'"
-  echo "${objout}"
-  exit 1
+  error "Unable to remove .cmdline from input: ${objout}"
 fi
 
 TEMP_KCL="$(mktemp)"
@@ -102,29 +130,27 @@ TEMP_KCL="$(mktemp)"
 if [ -n "${ARG_VAR}" ]; then
   echo -n "${ARG_VAR}" > "${TEMP_KCL}"
 elif [ -n "${ARG_FILE}" ]; then
-  cp "${ARG_FILE}" "${TEMP_KCL}" || exit 1
+  if ! cp "${ARG_FILE}" "${TEMP_KCL}"; then
+    error "Failed to copy argument file"
+  fi
 else
   if ! objout="$( objcopy --dump-section .cmdline="${TEMP_KCL}" "${INPUT_EFI}" 2>&1 )"; then
-    echo "Unable to extract cmdline from '${INPUT_EFI}'"
-    echo "${objout}"
-    exit 1
+    error "Unable to extract cmdline from input: ${objout}"
   fi
 
   clean_kcl "${TEMP_KCL}"
 
-  if ((PRINT_ONLY)); then
+  if [ -n "${PRINT_ONLY}" ]; then
     cat "${TEMP_KCL}"
     exit
   fi
 
   if ! command -v "${EDITOR:=vi}" >/dev/null 2>&1 ; then
-    echo "define \$EDITOR to edit"
-    exit 1
+    error "Define \$EDITOR to edit"
   fi
 
   if ! "${EDITOR}" "${TEMP_KCL}"; then
-    echo "failed to edit KCL for ${INPUT_EFI}"
-    exit 1
+    error "Failed to edit kernel command-line for input EFI executable"
   fi
 fi
 
@@ -138,14 +164,14 @@ sed -i 's/^/ /' "${TEMP_KCL}"
 echo -ne "\x00" >> "${TEMP_KCL}"
 
 if objout="$( objcopy --add-section .cmdline="${TEMP_KCL}" --change-section-vma .cmdline=0x30000 "${TEMP_EFI}" 2>&1 )"; then
-  if ! cp "${TEMP_EFI}" "${OUTPUT_EFI}" ; then
-    echo "Unable to copy ${TEMP_EFI} to ${OUTPUT}"
-    echo "Preserving '${TEMP_EFI}'"
-    PRESERVE_TEMP_EFI=1
-    exit 1
+  if [ -n "${OUTPUT_EFI}" ]; then
+    if ! cp "${TEMP_EFI}" "${OUTPUT_EFI}" ; then
+      PRESERVE_TEMP_EFI=1
+      error "Unable to save to ${OUTPUT}, saved as ${TEMP_EFI}"
+    fi
+  else
+    cat "${TEMP_EFI}"
   fi
 else
-  echo "Unable to add commandline to ${TEMP_KCL}"
-  echo "${objout}"
-  exit 1
+  error "Unable to add command line: ${objout}"
 fi
